name: Deployment

on:
  workflow_dispatch:
    inputs:
      deployChannels:
        description: 'Channels to deploy'
        required: true

jobs:
  deploy_webhooks:
    name: Build and deploy webhooks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3
      - name: Use Node.js v16
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # tag=v3
        with:
          node-version: 16
          cache: yarn
      - name: Install Dependencies
        run: yarn --immutable
      - name: Restore dist cache
        uses: actions/cache@9b0c1fce7a93df8e3bb8926b0d6e9d89e92f20a7 # tag=v3.0.11
        id: dist-cache-restore
        with:
          path: dist
          key: ${{ runner.os }}-16-${{ hashFiles('src/resource-webhooks.ts') }}
      - name: Build Code
        if: ${{ !steps.dist-cache-restore.outputs.cache-hit }}
        run: yarn build
      - name: Run deploy code
        run: yarn deploy
        env:
          WELCOME: ${{ secrets.WEBHOOK_WELCOME }}
          RELEASE: ${{ secrets.WEBHOOK_RELEASE }}
          DRAFT: ${{ secrets.WEBHOOK_DRAFT }}
          DEPLOY_CHANNELS: ${{ github.event.inputs.deployChannels }}
