name: Deployment

on:
  workflow_dispatch:
    inputs:
      deployChannels:
        description: 'Channels to deploy'
        required: true

jobs:
  deploy_webhooks:
    name: Build and deploy webhooks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # tag=v3
      - name: Use Node.js v16
        uses: actions/setup-node@5b52f097d36d4b0b2f94ed6de710023fbb8b2236 # tag=v3
        with:
          node-version: 16
          cache: yarn
      - name: Install Dependencies
        run: yarn --frozen-lockfile
      - name: Restore dist cache
        uses: actions/cache@4b0cf6cc4619e737324ddfcec08fff2413359514 # tag=v3.0.0
        id: dist-cache-restore
        with:
          path: dist
          key: ${{ runner.os }}-16-${{ hashFiles('src/resource-webhooks.ts') }}
      - name: Build Code
        if: ${{ !steps.dist-cache-restore.outputs.cache-hit }}
        run: yarn build
      - name: Run deploy code
        run: yarn deploy
        env:
          WELCOME: ${{ secrets.WEBHOOK_WELCOME }}
          RELEASE: ${{ secrets.WEBHOOK_RELEASE }}
          DRAFT: ${{ secrets.WEBHOOK_DRAFT }}
          WEBHOOK_AVATAR: ${{ secrets.WEBHOOK_AVATAR }}
          WEBHOOK_NAME: ${{ secrets.WEBHOOK_NAME }}
          DEPLOY_CHANNELS: ${{ github.event.inputs.deployChannels }}
