name: Deployment

on:
  workflow_dispatch:
    inputs:
      deployChannels:
        description: 'Channels to deploy'
        required: true

jobs:
  deploy_webhooks:
    name: Build and deploy webhooks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
      - name: Use Node.js v16
        uses: actions/setup-node@2fddd8803e2f5c9604345a0b591c3020ee971a93 # tag=v3
        with:
          node-version: 16
          cache: yarn
      - name: Install Dependencies
        run: yarn --immutable
      - name: Restore dist cache
        uses: actions/cache@fd5de65bc895cf536527842281bea11763fefd77 # tag=v3.0.8
        id: dist-cache-restore
        with:
          path: dist
          key: ${{ runner.os }}-16-${{ hashFiles('src/resource-webhooks.ts') }}
      - name: Build Code
        if: ${{ !steps.dist-cache-restore.outputs.cache-hit }}
        run: yarn build
      - name: Run deploy code
        run: yarn deploy
        env:
          WELCOME: ${{ secrets.WEBHOOK_WELCOME }}
          RELEASE: ${{ secrets.WEBHOOK_RELEASE }}
          DRAFT: ${{ secrets.WEBHOOK_DRAFT }}
          WEBHOOK_AVATAR: ${{ secrets.WEBHOOK_AVATAR }}
          WEBHOOK_NAME: ${{ secrets.WEBHOOK_NAME }}
          DEPLOY_CHANNELS: ${{ github.event.inputs.deployChannels }}
